### ISSUE TITLE
AddPhoto Bug

### ISSUE THREAD

**Issue by DillonMercz** [bgsald/instawebcircle#1]
const Insta = require('node-insta-web-api')
const InstaClient = new Insta();
const path = require("path")

async function uploadd() {
  //required username & password for login
  const username = '';
  const password = '';
  await InstaClient.login(username,password);
  await Insta.getCookie()
  const photo = path.join(__dirname, '/midimages/34567890p.png');
  await InstaClient.useExistingCookie();
  const resultAddPost = await InstaClient.addPost(photo, 'this is caption');
  console.log(resultAddPost)
}
uploadd()

/Users//Downloads/node_modules/node-insta-web-api/lib/index.js:89
            throw new Error('cookie format is wrong / expired, please try logging in again using function login().')
                  ^

Error: cookie format is wrong / expired, please try logging in again using function login().
    at Instagram.useExistingCookie (/Users//Downloads/node_modules/node-insta-web-api/lib/index.js:89:19)
    at async uploadd (/Users//Downloads/midinsta/insta.js:12:3)

Node.js v18.19.1

/Users//Downloads/node_modules/node-insta-web-api/lib/index.js:89
            throw new Error('cookie format is wrong / expired, please try logging in again using function login().')
                  ^

Error: cookie format is wrong / expired, please try logging in again using function login().
    at Instagram.useExistingCookie (/Users//Downloads/node_modules/node-insta-web-api/lib/index.js:89:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async uploadd (/Users//Downloads/midinsta/insta.js:13:3)

  await Insta.getCookie()
              ^

TypeError: Insta.getCookie is not a function
    at uploadd (/Users/Downloads/midinsta/insta.js:12:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.19.1

I am not sure if I did this right, but getCookie() is not a function and when I dont use it, I run into a cookie error.

**Comment by bgsald** [comment]
thk u
